server:
  port: 8001
spring:
  application:
    name: controller-name
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
jwt:
  config:
    key: zhangchi

