server:
  port: 8002
spring:
  application:
    name: web-name
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true
zuul:
  routes:
    base-name: #服务名称
      path: /user/** #配置请求URL的请求规则
      serviceId: base-name #指定Eureka注册中心中的服务id
jwt:
  config:
    key: zhangchi