server:
  port: 8006
spring:
  application:
    name: manager-name
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    controller-name:
      path: /test/** #配置请求URL的请求规则
      serviceId: manager-name #指定Eureka注册中心中的服务id
jwt:
  config:
    key: zhangchi